// Generated by CoffeeScript 1.9.1
(function() {
  var Client, Kefir, somata,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  somata = require('somata');

  Kefir = require('kefir');

  Client = (function(superClass) {
    extend(Client, superClass);

    function Client() {
      return Client.__super__.constructor.apply(this, arguments);
    }

    Client.prototype.subscribe = function() {
      var args, service_name, type;
      service_name = arguments[0], type = arguments[1], args = 3 <= arguments.length ? slice.call(arguments, 2) : [];
      return Kefir.stream((function(_this) {
        return function(emitter) {
          return Client.__super__.subscribe.apply(_this, [service_name, type].concat(slice.call(args), [function(err, event) {
            return emitter.emit(event);
          }]));
        };
      })(this));
    };

    return Client;

  })(somata.Client);

  module.exports = {
    Client: Client
  };

}).call(this);
